[package]
name = "figex-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "figex-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4", features = ["derive"] }
dirs = "6"
figex-cli-core = { path = "../core" }
figlet-rs = "1.0.0"
owo-colors = "4.3.0"
rust-embed = "8.11.0"
serde = { version = "1", features = ["derive"] }
toml = "0.9.8"
